package dev.feigo.triagemate.core.analyze

import dev.feigo.triagemate.core.model.Confidence
import dev.feigo.triagemate.core.model.Severity
import dev.feigo.triagemate.core.model.TriageReport

class FakeTriageAnalyzer : TriageAnalyzer {
    override suspend fun analyze(context: String, rawLog: String): TriageReport {
        val log = rawLog.lowercase()
        val (severity, title) = when {
            "nullpointerexception" in log -> Severity.HIGH to "Crash: NullPointerException"
            "illegalstateexception" in log -> Severity.MEDIUM to "Crash: IllegalStateException"
            else -> Severity.LOW to "Issue: Unknown crash"
        }

        return TriageReport(
            title = title,
            summary = "Generated by FakeTriageAnalyzer. Replace with Gemini in Week 4.",
            severity = severity,
            confidence = if (severity == Severity.LOW) Confidence.LOW else Confidence.MEDIUM,
            suspectedCauses = listOf("Missing null-check", "Race condition in UI state"),
            whereToLook = listOf("Stacktrace top frames", "Recent changes in related feature"),
            reproSteps = listOf(
                "Reproduce with the same flow",
                "Try slow network / background-resume"
            ),
            questionsNeeded = listOf("App version/build?", "Device/OS?", "Steps before crash?"),
            nextSteps = listOf(
                "Add guard + logging",
                "Add unit test for state",
                "Verify UI enablement logic"
            )
        )
    }
}